security:
    # Configuration des encoders pour les mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # Configuration des firewalls
    firewalls:
        # Le firewall "main" est utilisé pour l'authentification
        main:
            anonymous: true  # Permet aux utilisateurs non authentifiés d'accéder
            form_login:
                login_path: login  # chemin de la page de connexion
                check_path: login  # chemin pour soumettre le formulaire
                username_parameter: _username  # Paramètre d'authentification
                password_parameter: _password  # Paramètre de mot de passe
                default_target_path: portfolio_home  # Redirige vers la page d'accueil après connexion
            logout:
                path: logout  # chemin pour se déconnecter
                target: /  # Redirige après déconnexion vers la page d'accueil
    # Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Contrôles d'accès pour les utilisateurs
    access_control:
        # Les utilisateurs non authentifiés peuvent accéder à ces pages
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/photos$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Les utilisateurs connectés seulement peuvent accéder à ces pages suivantes :
        - { path: ^/reference$, roles: ROLE_USER }
        - { path: ^/dashboard$, roles: ROLE_ADMIN }
        - { path: ^/test-password$, roles: ROLE_ADMIN }
        - { path: ^/album/new$, roles: ROLE_ADMIN }
        - { path: ^/photo/upload$, roles: ROLE_ADMIN }
