version: '3.7'

services:
  # Service PHP avec FPM
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - database

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Assure-toi que le fichier nginx.conf est monté ici
    ports:
      - "8000:80"
    networks:
      - symfony_network
    depends_on:
      - php

  # Service PostgreSQL
  database:
    image: postgres:16-alpine
    container_name: symfony_database
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
