portfolio_home:
    path: /
    controller: App\Controller\PortFolioController::index
hello_world:
    path: /hello_world
    controller: App\Controller\HelloWorldController::index

# photo_index:
#     path: /photos
#     controller: App\Controller\PhotoController::index

photo_upload:
    path: /photo/upload
    controller: App\Controller\PhotoController::upload

album:
    path: /photo/album
    controller: App\Controller\AlbumController::index

reference:
    path: /reference
    controller: App\Controller\ReferenceController::index

photo_albums:
    path: /photos
    controller: App\Controller\PhotoController::albums

photos_by_album:
    path: /album/{id}
    controller: App\Controller\PhotoController::photosByAlbum