portfolio_home:
    path: /
    controller: App\Controller\PortFolioController::index

hello_world:
    path: /hello_world
    controller: App\Controller\HelloWorldController::index

photo_upload:
    path: /photo/upload
    controller: App\Controller\PhotoController::upload

album:
    path: /photo/album
    controller: App\Controller\AlbumController::index

reference:
    path: /reference
    controller: App\Controller\ReferenceController::index

photo_albums:
    path: /photos
    controller: App\Controller\PhotoController::albums

photos_by_album:
    path: /album/{id}
    controller: App\Controller\PhotoController::photosByAlbum
    requirements:
        id: '\d+'  # Cela indique que l'ID doit être un entier  

album_new:
    path: /album/new
    controller: App\Controller\AlbumController::new

rename_album:
  path: /albums/rename/{id}
  controller: App\Controller\PhotoController::renameAlbum

delete_album:
  path: /albums/delete/{id}
  controller: App\Controller\PhotoController::deleteAlbum

rename_photos:
  path: /photo/rename/{id}
  controller: App\Controller\PhotoController::renamePhoto

delete_photo:
  path: /photo/delete/{id}
  controller: App\Controller\PhotoController::deletePhoto